### ISSUE TITLE
Merging morphological snakes into `scikit-image`

### ISSUE THREAD

**Issue by soupault** [pmneila/morphsnakes#10]
Hello!

First of all, very nice work! Thanks a lot for the implementation, and for the examples you prepared!

I was wondering if you would consider merging these algorithms (i.e. the full repo) into `scikit-image` (scikit-image.org, https://github.com/scikit-image/scikit-image). It is one of the most popular libraries for image processing, and is fully written in Python/Cython.
If you find this proposal interesting, I'd be happy to assist you with the Pull Request.

In any case, thanks again, and keep up the great work! ;)

**Comment by pmneila** [comment]
Hi,

It is definitely in my TODO list. However, there are a few things to do before and I don't have a lot of time lately.  I should modify the code to follow the guidelines of the `scikit-image` project.

Also, there is a faster C++/Cython implementation in the `develop` branch of `morphsnakes` which (I think) should be the one merged in `skimage`, but I haven't tested properly. What's the criterion of the `scikit-image` project about this? Is a simple pure Python implementation preferable over a more complex but faster one in C++?

In any case, given that there is interest in the project being merged, I will start working on it.

**Comment by soupault** [comment]
>Also, there is a faster C++/Cython implementation in the develop branch of morphsnakes which (I think) should be the one merged in skimage, but I haven't tested properly. What's the criterion of the scikit-image project about this?

We position the library as pure Python+Cython (i.e. we do not accept and/or ship any C++ code (actually, there is some, but it is distributed as a reference code, and is not used)).

If you agree to incorporate the code into `scikit-image`, it would be better to do this in the least "harmful" way. For example, if we add grayscale/singlechannel implementations with one PR, and then update the implementations with color/multichannel support in another PR, it is better to keep the API consistent across steps. In most of cases, any breaking changes in the API should be made via deprecation procedure (for several releases). So, it is better to think in advance (I'd assist you in this, of course).
Above said, I think, we could proceed with 2D implementations, then add 2D+C support, and then Cythonize the implementations (of course, in case of availability of resources).

One more thing: we are slightly inclined to have the processing routines implemented as functions, not classes, but that is debatable.

For new functionality, we require an implementation, tests, and a gallery example (http://scikit-image.org/docs/dev/auto_examples/). The very information is duplicated in a PR template. We also have a howto on contributing (http://scikit-image.org/docs/dev/contribute.html), and a page where we describe the way images are used and processed across the lib (http://scikit-image.org/docs/dev/user_guide/data_types.html).

P.S. If you agree with the above, you could go ahead right away. Just open a PR (even "work-in-progress"), the core team will provide you its feedback, and support you in any questionable moments.

Regards

**Comment by soupault** [comment]
@pmneila Thanks a lot for your work! Closing as the suggestion has been addressed via https://github.com/scikit-image/scikit-image/pull/2791.
