### ISSUE TITLE
getting black images instead of results

### ISSUE THREAD

**Issue by widedh** [pmneila/morphsnakes#19]
Hi all, 
I am trying to implement the code, I didn't make any change. However, I can't get the correct outputs as shown in the example repository. Can anyone help me, please?
Thank you

here is the result I get:
![image](https://user-images.githubusercontent.com/29757195/60517713-6efa1000-9ce0-11e9-87c1-7182b36a69cb.png)

**Comment by TeddybearCrisis** [comment]
same thing here. 

**Update**
This appears to be a PyCharm issue. When I run the code from the command line it runs smoothly:
`python examples.py`

![image](https://user-images.githubusercontent.com/19166849/62560837-2f45bb80-b87e-11e9-991a-f6b71a7a8455.png)

**Comment by pmneila** [comment]
@TeddybearCrisis That's interesting. I wasn't able to reproduce the problem. Thank you for the hint.

@widedh Could you confirm you were using PyCharm?
