### ISSUE TITLE
Saving segmentation

### ISSUE THREAD

**Issue by MarDos1234** [pmneila/morphsnakes#20]
Hi,

I do not have much experience with python, could you please help me how can I save segmentation into nii binary file?

Thank you

Mark

**Comment by pmneila** [comment]
Hi,

I don't have a lot of experience with the nii format, but you can export any NumPy array to a nii file as explained in the [NiBabel web](https://nipy.org/nibabel/gettingstarted.html).

I guess this should work (I haven't tried it):

```python
import nibabel as nib

# Run levelset segmentation
levelset = ms.morphological_chan_vese(...)

# Convert the array to a Nifti image
img = nib.Nifti1Image(levelset, np.eye(4))
# Save the image
img.to_filename("levelset.nii.gz")
```

If you don't have `nibabel` installed, you can do it with `pip install nibabel`.
