### ISSUE TITLE
What‘s the role of ISoSI

### ISSUE THREAD

**Issue by JunMa11** [pmneila/morphsnakes#21]
Dear @pmneila ,

Thanks for sharing the great work.

In the PAMI 2014 paper, both GAC and ACWE use `SIoIS` operator.

![image](https://user-images.githubusercontent.com/19947331/68843623-63453e00-0703-11ea-9a6a-3254941c4cf1.png)

![image](https://user-images.githubusercontent.com/19947331/68843641-6dffd300-0703-11ea-93b1-4f269d2c955a.png)

However, in the code, **why `ISoSI` is also used?**
https://github.com/pmneila/morphsnakes/blob/aab66e70f86308d7b1927d76869a1a562120f849/morphsnakes.py#L136-L138

Best,
Jun

**Comment by pmneila** [comment]
Hi @JunMa11,

That's a good question. First, theoretically, ISoSI has the same _smoothing properties_ as SIoIS (in other words, in the mathematical derivations of the PAMI paper you can exchange IS and SI and reach the same conclusions). 

Now, the reason of alternating between SIoIS and ISoSI in practice comes just from experimental observation. We realized that the segmentations with alternation had slightly better quality than without it.

In any case, you can safely remove ISoSI and use only SIoIS. The algorithm will still work as expected.

Hope that answers your question.

Best

**Comment by JunMa11** [comment]
Hi @pmneila ,

Thanks for your answer very much.
