### ISSUE TITLE
How can ı calculate numbre of pixels in nodule ?

### ISSUE THREAD

**Issue by miracdogan** [pmneila/morphsnakes#22]
Hi, I want to calculate number of pixels in  `example_nodule()`'s example.  How can ı do ? Because I want to find area for selected zone. 

Thank you.

@pmneila

**Comment by pmneila** [comment]
Hi,

First, you need to get the final level-set that `morphological_geodesic_active_contour` returns:
```python
ls = ms.morphological_geodesic_active_contour(gimg, iterations=45, 
                                              init_level_set=init_ls,
                                              smoothing=1, threshold=0.31,
                                              balloon=1, iter_callback=callback)
```

The number of pixels can be obtained counting the number of nonzero elements of the level-set,
```python
area = np.count_nonzero(ls)
```
or, given that the array is binary, just sum the content of the array:
```python
area = ls.sum()
```
Both should be equivalent in this case.
