### ISSUE TITLE
How to draw our circle more smooth ?

### ISSUE THREAD

**Issue by miracdogan** [pmneila/morphsnakes#24]
Hi, 
When we start our program after all iteration finished, the program gives us shape, how can we draw this shape more smoothly? 

Example:
![image](https://user-images.githubusercontent.com/29199537/77672310-cdb39800-6f99-11ea-89c5-044313db2360.png)

**Comment by pmneila** [comment]
Hi,

I'm not sure if I understand your question. In your image, the algorithm gives you A and you want to get F? In that case, it seems that F is just the convex hull of A. You can compute the convex hull using, for example, the function [`skimage.morphology.convex_hull.convex_hull_image`](https://scikit-image.org/docs/0.7.0/api/skimage.morphology.convex_hull.html#skimage.morphology.convex_hull.convex_hull_image) from `skimage`.

Does this solve your problem?

**Comment by miracdogan** [comment]
For example, the algorithm gives the red boundary but ı want to get yellow circle. 
I change the values (smoothing, ballon, etc) but it's not working. 

![yellow](https://user-images.githubusercontent.com/29199537/77828893-4861ec00-712f-11ea-98bf-030d35399dc0.jpg)

I hope, my question is more clear now.  
Should I still try this ?      `skimage.morphology.convex_hull.convex_hull_image` ?

**Comment by pmneila** [comment]
Oh, I see now. You are looking for the largest inscribed circle? This is not that easy. A circle is a very strong prior for active contours and I really doubt you can get this result just by setting the `smooth` parameter to a high value.

Perhaps the easiest (but not very correct) solution is to compute the inscribed circle in a post-processing step acting on the result of the morphsnake. You can compute the center of the circle as the center of the inside area of the morphsnake segmentation, and then compute the minimum distance to the border of the segmentation as the radius of the circle. This is not the most _correct_ solution, but maybe it is good enough for your purposes?

A better (but more involved) solution would be maximizing the area of the circle with respect to its center and its radius, applying constraints that keep the circle inside the morphsnakes segmentation. You can maximize this by gradient ascent and, every time the circle goes outside the segmentation, project it back inside. This might take some work to get it working properly, and it does not ensure that you will get the best circle, but in any case it will be better than the previous approach.

There are algorithms to find the [largest empty circle](https://en.wikipedia.org/wiki/Largest_empty_sphere). You might want to take a look at them as well if you want the best solution to this problem.
