### ISSUE TITLE
interaction of separate contours

### ISSUE THREAD

**Issue by CR10-dv** [pmneila/morphsnakes#25]
Hello,

When initiating a level set of multiple blobs using morphsnakes, is it possible to prevent them from merging?

Ciaran

**Comment by pmneila** [comment]
Hi

One of the main goals of morphsnakes is to allow topological changes of the contours (ie, allowing merge and split). So, in principle, morphsnakes is not designed to prevent this from happening.

That said, you can easily reproduce this behavior by running multiple instances of morphsnakes, once per blob, and find the areas where the blobs overlap after each iteration and set them to 0. This code shows the overall idea:

```Python
import morphsnakes as ms

def fix_overlapping_levelsets(levelsets):
    # I haven't run this code. It might contain errors

    # Find the areas where levelsets overlap
    mask = np.sum(levelsets, axis=0) > 1

    # Set overlapping regions to 0.
    for ls in levelsets:
        ls[mask] = 0

    return levelsets

# This code DOES NOT WORK. It just shows the overall idea.
levelsets = [init_levelset_blob1(), init_levelset_blob2(), ...]

levelsets = fix_overlapping_levelsets(levelsets)
for _ in range(NUM_ITERS):
    # Evolve each level set a few iterations (1 in this case, it can be also 2 or 3…)
    levelsets = [ms.morphological_chan_vese(image, iterations=1, init_level_set=ls) for ls in levelsets]
    levelsets = fix_overlapping_levelsets(levelsets)
```

Hope that helps!

**Comment by CR10-dv** [comment]
Hi,

Many thanks - that's really helpful. I was doing this yesterday - I was thinking of something along the lines of your turbopixel algorithm in your paper initially (do you have source code for this you can share? - no worries if not). I plan to eventually (hopefully) adapt it to the ideas in this paper for topological correction of map data (https://link.springer.com/article/10.1007/s00138-010-0294-8). Will share if I manage it!

**Comment by pmneila** [comment]
Hi again, @Ciaran1981 

Of course, you can use the technique of homotopic thinning to find the _walls_ between blobs and apply that as a mask after each iteration. The main disadvantage is that this approach is much slower. 

I don't think I have the entire code for the turbopixels, but I have the code I wrote for the [homotopic thinning](https://www.dropbox.com/s/9fvp2r3dhgi4vaq/skel.zip?dl=1) part. Keep in mind that I wrote it in C++ with a wrapper to Python using [Boost.Python](https://www.boost.org/doc/libs/1_66_0/libs/python/doc/html/index.html) and it can take some effort to compile it. After that, you can use this function to build the boundaries from the levelsets:

```Python
import _skel  # C++ module

def boundaries_from_contour(u, connectivity4=True):
    
    mask = np.logical_not(u)
    dist_transform = ndimage.distance_transform_edt(mask)
    #weigth = ndimage.laplace(dist_transform)
    weigth = 1/(1+dist_transform)
    _skel.homotopic_thinning(weigth, mask, connectivity4)
    return mask
```

In any case, I think the solution of my previous message is way simpler to implement and probably will lead to better results (although I haven't checked that).
