### ISSUE TITLE
implementing on 1. multiple objects and 2. donuts, and 3. a question about precision

### ISSUE THREAD

**Issue by SB2020-eye** [pmneila/morphsnakes#29]
Hi. Congratulations on such an impressive method.

I am very new to coding (and only know a little Python) and relatively new to image processing.

Here is one of my results of running ACWE on an image:

![folio_041r_cis_acwe_sm](https://user-images.githubusercontent.com/56878280/96619479-3cf52e80-12d4-11eb-9683-57dd414a2f39.png)

I am trying to segment the ink -- the handwritten letters -- on images with text like this, and wondering three things:

1. How could I capture multiple letters (even allowing for connected-letters, like the "ic" above) as separate objects at the same time? Like in the image above, how could I capture "s" separately from "ci"?

     Or imagine a word next to these letters (which there is in the original). How could I run morphsnakes to also do its work on those letters and words as well?

2. How would one isolate a donut-shaped object (like "ci" is, _almost_, in effect; or like a letter "o" or "d" would be)? I mean, how could I segment the ink without the inside as part of the result? Or even get the letter "s" to hug its borders better?

3. Lastly, how could I improve the precision of these results, so that tips aren't cropped (like the right side of the "i", top and bottom; or like the upper-right tip of the "s")?

(For one thing, I was wondering if donut-shapes hurt precision -- if the entire interior is being weighed against the exterior. That is, using my example image, a significant area of "not ink" in the donut hole of "ic" is being factored into results.)

Thank you for your consideration.

**Comment by pmneila** [comment]
Hi @SB2020-eye,

I answer your three questions separately.

> How could I capture multiple letters as separate objects at the same time?

Definitely not with morphsnakes. Morphsnakes work at a very low level of image understanding. They can find objects that are visually different from the background even when they have undefined, blurry or noisy boundaries. However, morphsnakes cannot split two objects based on their shape.

If this is critical for your problem, I'm afraid that morphsnakes is not the right tool for you. You need a tool that is capable of learning the shapes of the objects you want to distinguish.

> I mean, how could I segment the ink without the inside as part of the result?

You might be able to do so with a proper initialization of the levelset. I suggest that you use a checkerboard as a initial levelset (check `checkerboard_level_set`) with a small `square_size` (I think 5 should be fine for you).

> how could I improve the precision of these results, so that tips aren't cropped?

Smoothed tips are a consequence of one of the assumptions in the design of the morphsnakes algorithm: object boundaries are assumed to be smooth. However, you might get sharper corners by setting the `smoothing` parameter or `morphological_chan_vese` to a small value (even 0). However, note that this will make the algorithm more sensitive to image noise and might cause it fail when the letter boundaries are blurred.
