### ISSUE TITLE
not showing correct output

### ISSUE THREAD

**Issue by mudverma** [pmneila/morphsnakes#3]
Hi, 

Thanks for your code. I have been trying to play around it a bit. In that process, I cropped the image. However, the algo doesn't seem to give correct output. 

Original

![mini](https://cloud.githubusercontent.com/assets/4323340/12885850/2bbbd206-ce8f-11e5-924a-6deb74ec8c25.png)

Cropped: 

![world_out](https://cloud.githubusercontent.com/assets/4323340/12885853/31435f5a-ce8f-11e5-94a8-d8bf32091e9f.png)

Do you know what could be the issue?  

PS: cropping the image like this 

```
imgcolor = imread("testimages/seastar2.png")/255.0
imgcolor = imgcolor[50:250, 50:250]
```

**Comment by pmneila** [comment]
Hi,

You have to be careful that the initial contour is inside the image area. If you crop the image, you have to change the initialization of the contour accordingly.

In your case, you can use

``` python
mgac.levelset = circle_levelset(img.shape, (100, 100), 97, scalerow=1.0)
```

or something similar.

Hope that helps.
