### ISSUE TITLE
Can I extract a signed distance function from the output of morphsnakes ?

### ISSUE THREAD

**Issue by liubenyuan** [pmneila/morphsnakes#5]
Hi, I want to use `morphsnakes` as a tool for extracting the boundary of a CT/MRI scan of head.

![image](https://cloud.githubusercontent.com/assets/171338/14095000/1aefd636-f58e-11e5-8899-3f05127763ac.png)

I want to use the **red line** on the left figure as a function handler in python, denoted by `fd`. For all pixels `p = (x, y)`, it will be `fd(p) = 0` on the boundary, `fd(p) < 0` interior and `fd(p) > 0` at the exterior. I do not know whether `morphsnakes` support this feature (in both 2D and 3D!!), and is there any post processing techniques I need to achieve this goal ?

**Comment by pmneila** [comment]
You can easily compute the signed distance transform of the embedding function of the morphsnakes with the following function:

``` python
import numpy as np
from scipy import ndimage

def get_distance(f):
    """Return the signed distance to the 0.5 levelset of a function."""

    # Prepare the embedding function.
    f = f > 0.5

    # Signed distance transform
    dist_func = ndimage.distance_transform_edt
    distance = np.where(f, dist_func(f) - 0.5, -(dist_func(1-f) - 0.5))

    return distance
```

Pass the embedding function of the morphsnakes as input (`get_distance(msnake.levelset)`). It is valid for 2D and 3D.

**Comment by liubenyuan** [comment]
Thanks !
