### ISSUE TITLE
Open contours

### ISSUE THREAD

**Issue by petercheng00** [pmneila/morphsnakes#8]
Can this code/algorithm be modified to work with open contours? E.g. a curve rather than a closed shape.

**Comment by pmneila** [comment]
Hi,

In general, no, it cannot be done. However, if your open curve has fixed end-points (i.e., you know where the curve starts and ends) then it might be possible to simulate this behavior using a closed contour that passes through the end-points and updating only the fragment of the contour between the end-points. Whether this will work or not depends on your particular problem.

**Comment by petercheng00** [comment]
That's an interesting idea, I may give that a try. Thanks for the advice.
